name: Machine Learning CI Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  ml_ci_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Run actions/checkout@v3
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv pandas scikit-learn mlflow==2.19.0 dagshub

    - name: Run MLflow Project
      env:
        # Menghubungkan kredensial DagsHub secara aman via GitHub Secrets
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_CLIENT_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        cd MLProject
        mlflow run . --experiment-name="Diabetes_Retraining_Clean" --env-manager=local

    - name: Upload Training Artifacts to GitHub Repository
      uses: actions/upload-artifact@v4
      with:
          name: diabetes-model-artifacts
          path: |
            MLProject/mlruns/
            MLProject/target_model/
            MLProject/*.json
            MLProject/*.png
          retention-days: 7

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build MLflow Docker Image
      run: |
        docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model-hub:latest" -f MLProject/Dockerfile MLProject
        
        
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model-hub:latest
