name: Machine Learning CI Pipeline

on:
  push:
    branches: [ main, master ]

jobs:
  ml_ci_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'

    - name: Install Base Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv pandas scikit-learn mlflow==2.19.0 dagshub

    - name: Run MLflow Project (Retraining)
      env:
        # Menghubungkan kredensial DagsHub secara aman via GitHub Secrets
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_CLIENT_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        python modelling_tuning.py

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build MLflow Docker Image
      run: |
        cp -r mlruns/0/*/artifacts/model ./target_model
        mlflow models build-docker -m ./target_model -n "${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model-hub:latest"
        
        
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/diabetes-model-hub:latest
